### ISSUE TITLE
v5.0.0-beta2 - Favorites are mixed up

### ISSUE THREAD

**Issue by cgeroldinger** [johanfrick/custom-sonos-card#56]
On that Version i now see all my are now one below the other (picture 2)
Picture 1 showing 4.2.1
Help please.
![5 0 0-beta](https://user-images.githubusercontent.com/40886256/161217170-626141be-ed4c-4238-b390-1899a88c0a15.png)
![5 0 0 -beta2](https://user-images.githubusercontent.com/40886256/161217176-a1a22f0c-8784-45e8-aebe-fa57aac831b5.png)
.

Thanks

**Comment by johanfrick** [comment]
Thanks @cgeroldinger for reporting this. I've released another beta, could you please test and see how it behaves?
https://github.com/johanfrick/custom-sonos-card/releases/tag/v5.0.0-beta3

**Comment by cgeroldinger** [comment]
Still the same issue

![01EAD667-0780-42FF-9537-2D54230ABA0F](https://user-images.githubusercontent.com/40886256/161413655-93639945-e230-4d56-b32b-9ab7a5bb9334.jpeg)

**Comment by cgeroldinger** [comment]
Sorry.   Seem to be ok now with beta3

**Comment by jrspowers** [comment]
hey still the self as in beta 2 after installing beta 3 the media stays vertical only show half of the media?

**Comment by johanfrick** [comment]
You sure? Works both for me and @cgeroldinger 
Try and reload/restart maybe

**Comment by mfabiani53** [comment]
> hey still the self as in beta 2 after installing beta 3 the media stays vertical only show half of the media?

Same here.... all favourites stays vertical only also after installing beta 3

**Comment by jrspowers** [comment]
hey @johanfrick i just restarted home assistant and the result is still the same as before beta 3 ?

**Comment by johanfrick** [comment]
Really strange. It looks fine for me, but mine was messed up with beta2.
<img width="997" alt="image" src="https://user-images.githubusercontent.com/26582898/161444545-35797e82-3abb-4dc0-b741-bd05d0a69872.png">

**Comment by johanfrick** [comment]
Same issue with https://github.com/johanfrick/custom-sonos-card/releases/tag/v5.0.0-beta4 @jrspowers ?

**Comment by cgeroldinger** [comment]
Just updated to 5.0.0-beta4 - All good for me

Home Assistant OS 7.6
HA-Core -2022.3.8
Hacs-1.24.3
Sonos- 5.0.0-beta4

**Comment by jrspowers** [comment]
Still nothing changed after reboot and reload? @johanfrick ![image](https://user-images.githubusercontent.com/60328474/161488242-d4ed8cce-4db6-448a-8eb0-a164dfb1a649.png)

**Comment by johanfrick** [comment]
I'm afraid I'll close this one. I've released the non-beta for this feature, and other users report that it works fine.
